export const SHOPS = [
  {
    id: "shop1",
    name: "maru",
    products: [
      {
        id: "maru_postcard01",
        category: "ポストカード",
        name: "階段と鳩",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_postcard02",
        category: "ポストカード",
        name: "階段とワカケ",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_postcard03",
        category: "ポストカード",
        name: "崖とカモメ",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_postcard04",
        category: "ポストカード",
        name: "水辺",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_postcard05",
        category: "ポストカード",
        name: "コインランドリー",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_postcard06",
        category: "ポストカード",
        name: "建物の外観と鳩",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_sticker01",
        category: "シール",
        name: "猫",
        stock: 200,
        price: 200,
      },
      {
        id: "maru_sticker01",
        category: "シール",
        name: "猫",
        stock: 100,
        price: 200,
      },
      {
        id: "maru_sticker02",
        category: "シール",
        name: "鳩",
        stock: 100,
        price: 200,
      },
      {
        id: "maru_sticker03",
        category: "シール",
        name: "犬",
        stock: 100,
        price: 200,
      },
      {
        id: "maru_acrylicstand01",
        category: "アクスタ",
        name: "猫と遊具",
        stock: 10,
        price: 800,
      },
      {
        id: "maru_acrylicstand02",
        category: "アクスタ",
        name: "アリクイと遊具",
        stock: 10,
        price: 800,
      },
      {
        id: "maru_acrylicstand03",
        category: "アクスタ",
        name: "鳩と遊具",
        stock: 10,
        price: 800,
      },
      {
        id: "maru_canvas01",
        category: "キャンバスボード",
        name: "工場",
        stock: 10,
        price: 800,
      },
    ],
  },
  {
    id: "shop2",
    name: "MAIKO",
    products: [
      {
        id: "maiko_postcard01",
        category: "ポストカード",
        name: "うさぎとファミレス",
        stock: 200,
        price: 200,
      },
      {
        id: "maiko_postcard02",
        category: "ポストカード",
        name: "猫と階段",
        stock: 200,
        price: 200,
      },
      {
        id: "maiko_postcard03",
        category: "ポストカード",
        name: "うさぎと旅館",
        stock: 200,
        price: 200,
      },
      {
        id: "maiko_acrylickeyholder01",
        category: "アクキー",
        name: "飛行機",
        stock: 10,
        price: 800,
      },
      {
        id: "maiko_acrylickeyholder02",
        category: "アクキー",
        name: "夜の旅",
        stock: 10,
        price: 600,
      },
      {
        id: "maiko_postcard04",
        category: "ポストカード",
        name: "レンチキュラー",
        stock: 100,
        price: 400,
      },
      {
        id: "maiko_acrylicstand01",
        category: "アクスタ",
        name: "うさぎの星",
        stock: 10,
        price: 800,
      },
      {
        id: "maiko_acrylicstand02",
        category: "アクスタ",
        name: "さかなの星",
        stock: 10,
        price: 800,
      },
      {
        id: "maiko_sticker01",
        category: "シール",
        name: "丙午",
        stock: 100,
        price: 200,
      },
      {
        id: "maiko_sticker02",
        category: "シール",
        name: "おいしそうなうどん",
        stock: 100,
        price: 200,
      },
    ],
  },
];
